Change way adding nav entry to allow l10n
owncloud/market pull request #864
Opened 2021-12-17 08:52 UTC by JanAckermann

2021-12-17 10:36 UTC, DeepDiver1975 requested changes

2021-12-17 10:36 UTC, DeepDiver1975 commented on appinfo/info.xml
> -	<navigation role="admin">
Why was that removed?

2021-12-17 10:36 UTC, DeepDiver1975 commented on l10n/Makefile
> -LOCALES = af_ZA  bg_BG  ca  cs_CZ  da  de  de_DE  el  en_GB  es  et_EE  fi_FI  fr  he  hu_HU  is  it  ja  ko  lt_LT  nb_NO  nl  oc  pl  pt_BR  pt_PT  ru  sl  sq  sv  th_TH  tr  uk  zh_CN
oc no longer on transifex I assume?

2021-12-17 10:40 UTC, JanAckermann commented on appinfo/info.xml
> -	<navigation role="admin">
Added here: lib/Application.php to allow translations

2021-12-17 10:41 UTC, JanAckermann commented on l10n/Makefile
> -LOCALES = af_ZA  bg_BG  ca  cs_CZ  da  de  de_DE  el  en_GB  es  et_EE  fi_FI  fr  he  hu_HU  is  it  ja  ko  lt_LT  nb_NO  nl  oc  pl  pt_BR  pt_PT  ru  sl  sq  sv  th_TH  tr  uk  zh_CN
we don't have min percentage of 15% translations here (so .po file won't be pulled), therefore the command `gettext-compile --output translations.json $(LOCALE_FILES)` fails

2021-12-20 09:02 UTC, JanAckermann commented on appinfo/info.xml
> -	<navigation role="admin">
Let me revert this and check if it works now, l10n should be there now =)

2021-12-22 11:25 UTC, DeepDiver1975 approved these changes

2021-12-22 11:46 UTC, merged